### ISSUE TITLE
1.14.4 Error

### ISSUE THREAD

**Issue by Rix4Soul** [Shugo-Daimyo/Solo-Sleep#1]
does not work on version 1,14,4
PeperSpigot

**Comment by Shugo-Daimyo** [comment]
Any errors in console? Either on startup or on sleep?

**Comment by Rix4Soul** [comment]
I manually changed in the plugin "plugin.yml " api-version: "1.15" --> api-version: "1.14" and now everything works!

**Comment by Rix4Soul** [comment]
Но, когда люди ложатся на кровать, у них виснет игра и вылетает!

**Comment by Rix4Soul** [comment]
But when people lie down on the bed, they hang the game and crashes!

**Comment by Rix4Soul** [comment]
[16:05:32] [Server thread/ERROR]: Could not load 'plugins/Solo-Sleep-1.0-SNAPSHOT.jar' in folder 'pl$
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.15
        at org.bukkit.craftbukkit.v1_14_R1.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.j$
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:130) ~[patched1$
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:337) ~[patched$
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:257) ~[patched$
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:355) ~[patched_1$
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:226) ~[patched_1.$
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.1$
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Shugo-Daimyo** [comment]
Okay will work on an update now, I had misinterpreted the usage of the api-version flag for the plugin.yml

Will update with a download link when it's complete

**Comment by Shugo-Daimyo** [comment]
Pushed a fix, download the update on the SpigotMC page [here](https://www.spigotmc.org/resources/solo-sleep.77691/).

Closed
